event_inherited();
randomize();
BulletDirection = 0;
EnemyFireRate = 180;
ShootTimer = EnemyFireRate;
EnemyHP = 50;
MoveDir = -1;
DetectionRange = room_width/3;
HMovement_Push = 0;
sprite_index = sprBanditIdle;